apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nodeappdeployment
  labels:
    type: backend
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      type: backend
      app: nodeapp
  template:
    metadata:
      labels:
        type: backend
        app: nodeapp
    spec:
      containers:
        - name: nodeappcontainer
          image: us-central1-docker.pkg.dev/youtube-431617/my-images/nodeapp:v1
          ports:
            - containerPort: 80